### ISSUE TITLE
Ubuntu 20.04: Harfbuzz version too old

### ISSUE THREAD

**Issue by Torsten-K** [i38/justmd#4]
(justmd:6251): Pango-ERROR **: 00:00:46.346: Harfbuzz version too old (1.4.2)

Will there be an updated version of justmd, or is the development stopped?

**Comment by x1y9** [comment]
When did you see this error?

**Comment by Torsten-K** [comment]
I saw this in September 2020 and also today, April 29th 2021. My system is GNU/Linux, distribution Xubuntu 20.10.

**Comment by x1y9** [comment]
It seems that higher versions of linux are not downward compatible with lower versions of electron, here is a temporary solution：
https://github.com/electron/electron/issues/20348#issuecomment-635378964

I'll try to update to a new version of electron in a later release and maybe fix this issue as well.

**Comment by Torsten-K** [comment]
v1.2.1 works on Xubuntu 21.04, thanks for updating!
